"""initial schema

Revision ID: dc40e875d392
Revises: 
Create Date: 2026-04-20 01:02:25.408581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc40e875d392'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('computers', sa.Integer(), nullable=True),
    sa.Column('servers', sa.Integer(), nullable=True),
    sa.Column('email_platform', sa.String(length=120), nullable=True),
    sa.Column('internet_provider', sa.String(length=120), nullable=True),
    sa.Column('antivirus', sa.Boolean(), nullable=True),
    sa.Column('backups', sa.Boolean(), nullable=True),
    sa.Column('mfa', sa.Boolean(), nullable=True),
    sa.Column('selected_services', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_onboarding')
    # ### end Alembic commands ###
